[[redirects]] 
 from = "/signin" 
 to = "/index.html" 
 status = 200 
  
 [[redirects]] 
 from = "/home"   
 to = "/index.html" 
 status = 200 
  
 [[redirects]] 
 from = "/tasks"  
 to = "/index.html" 
 status = 200 
  
  
 [[redirects]] 
 from = "/notfound"   
 to = "/path/to/404/page"   
 status = 404 
 